/* Generated by pack-enhanced-graphics.py; do not edit. */
#define ENHANCED_TOWN_TILE_COUNT 69
#define ENHANCED_TERRAIN_TILE_BASE 171
#define ENHANCED_TERRAIN_TILE_COUNT 18
#define ENHANCED_WORLD_TILE_COUNT 87
static const UBYTE enhancedTownTileOffsets[8] = {0, 3, 9, 15, 30, 45, 51, 57};
