/* Generated by pack-enhanced-graphics.py; do not edit. */
static const UBYTE enhancedProjectileHardwareCompatible[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const UBYTE enhancedBombOriginal[2] = {0, 0};
