/* Generated by tools/promote_cpc_assets.py. Do not hand-edit raw arrays.
   Source of truth: amiga/assets/generated/cpc/cpc_plus_sprites.json
                    amiga/assets/generated/cpc/cpc_object_blocks.json
   Polished/native derivatives should be separate assets that cite these source ids. */
#ifndef HAR_CPC_PROMOTED_ASSETS_H
#define HAR_CPC_PROMOTED_ASSETS_H

#define HAR_CPC_PROMOTED_ASSET_COUNT 20
#define HAR_CPC_TOWN_BLOCK_COUNT 8
#define HAR_CPC_TOWN_BLOCK_HEIGHT 5

/* harrier_flying_left: Flying Harrier left/green half
   CPC source: AMSTRADFONT3.asm:1594
   CPC asset id: sprite_pixel_data1 */
#define HAR_CPC_HARRIER_FLYING_LEFT_WIDTH 16
#define HAR_CPC_HARRIER_FLYING_LEFT_HEIGHT 8
static const UBYTE harCpcHarrierFlyingLeftPixels[128] = {
	11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 11, 0, 0, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0,
	9, 10, 11, 0, 0, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 9, 10, 10, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 8, 8, 7, 7, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 8, 7, 0, 0, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 8, 9, 10, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* harrier_flying_right: Flying Harrier right/green half
   CPC source: AMSTRADFONT3.asm:1603
   CPC asset id: sprite_pixel_data2 */
#define HAR_CPC_HARRIER_FLYING_RIGHT_WIDTH 16
#define HAR_CPC_HARRIER_FLYING_RIGHT_HEIGHT 8
static const UBYTE harCpcHarrierFlyingRightPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 11, 11, 10, 11, 12, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 10, 9, 8, 7, 10, 9, 8, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 11, 9, 8, 7, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 7, 7, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* harrier_landing_left: Landing Harrier left half
   CPC source: AMSTRADFONT3.asm:1636
   CPC asset id: sprite_pixel_data4 */
#define HAR_CPC_HARRIER_LANDING_LEFT_WIDTH 16
#define HAR_CPC_HARRIER_LANDING_LEFT_HEIGHT 8
static const UBYTE harCpcHarrierLandingLeftPixels[128] = {
	11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 9, 10, 10, 10, 9, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	7, 8, 8, 9, 8, 9, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 7, 7, 8, 8, 9, 7, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* harrier_landing_right: Landing Harrier right half
   CPC source: AMSTRADFONT3.asm:1645
   CPC asset id: sprite_pixel_data3 */
#define HAR_CPC_HARRIER_LANDING_RIGHT_WIDTH 16
#define HAR_CPC_HARRIER_LANDING_RIGHT_HEIGHT 8
static const UBYTE harCpcHarrierLandingRightPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 10, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 9, 8, 10, 11, 12, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 9, 8, 7, 9, 9, 10, 9, 0, 0, 0, 0, 0, 0, 0, 0,
	7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* enemy_plane_flying_left: Enemy plane flying left half
   CPC source: AMSTRADFONT3.asm:1658
   CPC asset id: sprite_pixel_data5 */
#define HAR_CPC_ENEMY_PLANE_FLYING_LEFT_WIDTH 16
#define HAR_CPC_ENEMY_PLANE_FLYING_LEFT_HEIGHT 8
static const UBYTE harCpcEnemyPlaneFlyingLeftPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 6, 5, 4, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 4, 4, 5, 4, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 5, 4, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 3, 3, 2, 2, 1, 3, 6, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* enemy_plane_flying_right: Enemy plane flying right half
   CPC source: AMSTRADFONT3.asm:1667
   CPC asset id: sprite_pixel_data6 */
#define HAR_CPC_ENEMY_PLANE_FLYING_RIGHT_WIDTH 16
#define HAR_CPC_ENEMY_PLANE_FLYING_RIGHT_HEIGHT 8
static const UBYTE harCpcEnemyPlaneFlyingRightPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 3, 2, 0, 0, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 3, 2, 1, 0, 6, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 5, 5, 5, 5, 4, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 4, 3, 3, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 4, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 6, 5, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 6, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* enemy_plane_broken_left: Enemy plane broken left half
   CPC source: AMSTRADFONT3.asm:1678
   CPC asset id: sprite_pixel_data7 */
#define HAR_CPC_ENEMY_PLANE_BROKEN_LEFT_WIDTH 16
#define HAR_CPC_ENEMY_PLANE_BROKEN_LEFT_HEIGHT 8
static const UBYTE harCpcEnemyPlaneBrokenLeftPixels[128] = {
	0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 6, 3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 6, 3, 4, 1, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 6, 4, 3, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 4, 3, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* enemy_plane_broken_right: Enemy plane broken right half
   CPC source: AMSTRADFONT3.asm:1688
   CPC asset id: sprite_pixel_data8 */
#define HAR_CPC_ENEMY_PLANE_BROKEN_RIGHT_WIDTH 16
#define HAR_CPC_ENEMY_PLANE_BROKEN_RIGHT_HEIGHT 8
static const UBYTE harCpcEnemyPlaneBrokenRightPixels[128] = {
	3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 3, 4, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 4, 3, 3, 4, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 2, 4, 3, 3, 3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 3, 4, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* carrier_body: Carrier body
   CPC source: AMSTRADFONT3.asm:1710
   CPC asset id: sprite_pixel_data10 */
#define HAR_CPC_CARRIER_BODY_WIDTH 16
#define HAR_CPC_CARRIER_BODY_HEIGHT 8
static const UBYTE harCpcCarrierBodyPixels[128] = {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	5, 4, 5, 4, 5, 3, 5, 4, 5, 4, 5, 3, 4, 4, 5, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2
};

/* carrier_back: Carrier back
   CPC source: AMSTRADFONT3.asm:1721
   CPC asset id: sprite_pixel_data11 */
#define HAR_CPC_CARRIER_BACK_WIDTH 16
#define HAR_CPC_CARRIER_BACK_HEIGHT 8
static const UBYTE harCpcCarrierBackPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	0, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	0, 0, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2
};

/* carrier_front: Carrier front
   CPC source: AMSTRADFONT3.asm:1732
   CPC asset id: sprite_pixel_data12 */
#define HAR_CPC_CARRIER_FRONT_WIDTH 16
#define HAR_CPC_CARRIER_FRONT_HEIGHT 8
static const UBYTE harCpcCarrierFrontPixels[128] = {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 0,
	3, 3, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 2, 0, 0,
	4, 4, 4, 1, 6, 5, 4, 4, 4, 4, 4, 4, 2, 0, 0, 0,
	4, 4, 4, 6, 5, 1, 4, 4, 4, 4, 4, 2, 0, 0, 0, 0,
	3, 3, 6, 5, 1, 3, 3, 3, 3, 3, 2, 0, 0, 0, 0, 0,
	2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0
};

/* carrier_top: Carrier top
   CPC source: AMSTRADFONT3.asm:1743
   CPC asset id: sprite_pixel_data13 */
#define HAR_CPC_CARRIER_TOP_WIDTH 16
#define HAR_CPC_CARRIER_TOP_HEIGHT 16
static const UBYTE harCpcCarrierTopPixels[256] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 4, 4,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3,
	0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	0, 0, 0, 0, 1, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	1, 2, 3, 0, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 3,
	1, 2, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4
};

/* carrier_top_2: Carrier top 2
   CPC source: AMSTRADFONT3.asm:1763
   CPC asset id: sprite_pixel_data14 */
#define HAR_CPC_CARRIER_TOP_2_WIDTH 16
#define HAR_CPC_CARRIER_TOP_2_HEIGHT 16
static const UBYTE harCpcCarrierTop2Pixels[256] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 4, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 4, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 3, 3, 3, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 4, 4, 4, 4, 4, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0
};

/* gunship_left: Gunship left
   CPC source: AMSTRADFONT3.asm:1783
   CPC asset id: sprite_pixel_data15 */
#define HAR_CPC_GUNSHIP_LEFT_WIDTH 16
#define HAR_CPC_GUNSHIP_LEFT_HEIGHT 16
static const UBYTE harCpcGunshipLeftPixels[256] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
	0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3,
	0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 2, 2, 3, 3,
	0, 0, 0, 0, 0, 2, 0, 4, 3, 0, 0, 2, 0, 3, 3, 2,
	0, 0, 0, 0, 0, 0, 1, 3, 2, 0, 0, 2, 0, 2, 2, 2,
	1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3,
	0, 1, 2, 3, 4, 5, 6, 5, 5, 5, 4, 5, 4, 4, 4, 4,
	0, 0, 1, 1, 2, 3, 5, 6, 5, 5, 5, 4, 5, 4, 4, 4
};

/* gunship_right: Gunship right
   CPC source: AMSTRADFONT3.asm:1803
   CPC asset id: sprite_pixel_data16 */
#define HAR_CPC_GUNSHIP_RIGHT_WIDTH 16
#define HAR_CPC_GUNSHIP_RIGHT_HEIGHT 16
static const UBYTE harCpcGunshipRightPixels[256] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 1, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2, 1,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 2, 1, 1,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 2, 1, 1, 0
};

/* wingman_flying_left: Wingman flying left half
   CPC source: AMSTRADFONT3.asm:1823
   CPC asset id: sprite_pixel_data_wingmanflying1 */
#define HAR_CPC_WINGMAN_FLYING_LEFT_WIDTH 16
#define HAR_CPC_WINGMAN_FLYING_LEFT_HEIGHT 8
static const UBYTE harCpcWingmanFlyingLeftPixels[128] = {
	5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 5, 0, 0, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 4, 5, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 3, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 2, 2, 1, 1, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 2, 1, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 2, 3, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* wingman_flying_right: Wingman flying right half
   CPC source: AMSTRADFONT3.asm:1832
   CPC asset id: sprite_pixel_data_wingmanflying2 */
#define HAR_CPC_WINGMAN_FLYING_RIGHT_WIDTH 16
#define HAR_CPC_WINGMAN_FLYING_RIGHT_HEIGHT 8
static const UBYTE harCpcWingmanFlyingRightPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 5, 5, 4, 5, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 4, 3, 2, 1, 4, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 5, 3, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* wingman_landed_left: Wingman landed left half
   CPC source: AMSTRADFONT3.asm:1843
   CPC asset id: sprite_pixel_data_wingmanlanded1 */
#define HAR_CPC_WINGMAN_LANDED_LEFT_WIDTH 16
#define HAR_CPC_WINGMAN_LANDED_LEFT_HEIGHT 8
static const UBYTE harCpcWingmanLandedLeftPixels[128] = {
	5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 3, 4, 4, 4, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 2, 2, 3, 2, 3, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 1, 1, 2, 2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* wingman_landed_right: Wingman landed right half
   CPC source: AMSTRADFONT3.asm:1852
   CPC asset id: sprite_pixel_data_wingmanlanded2 */
#define HAR_CPC_WINGMAN_LANDED_RIGHT_WIDTH 16
#define HAR_CPC_WINGMAN_LANDED_RIGHT_HEIGHT 8
static const UBYTE harCpcWingmanLandedRightPixels[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 3, 2, 4, 5, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	2, 3, 2, 1, 3, 3, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* parachute: Parachute
   CPC source: AMSTRADFONT3.asm:1863
   CPC asset id: sprite_pixel_data_parachute */
#define HAR_CPC_PARACHUTE_WIDTH 16
#define HAR_CPC_PARACHUTE_HEIGHT 8
static const UBYTE harCpcParachutePixels[128] = {
	0, 0, 0, 15, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 15, 15, 15, 15, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	15, 15, 15, 15, 15, 15, 15, 15, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* town_block_0: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5878
   CPC asset id: town_block_0
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_0_WIDTH 1
static const UBYTE harCpcTownBlock0Tiles[5] = {
	0, 0, 66, 1, 1
};

/* town_block_1: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5879
   CPC asset id: town_block_1
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_1_WIDTH 2
static const UBYTE harCpcTownBlock1Tiles[10] = {
	0, 0, 70, 1, 1, 0, 0, 71, 1, 1
};

/* town_block_2: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5880
   CPC asset id: town_block_2
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_2_WIDTH 2
static const UBYTE harCpcTownBlock2Tiles[10] = {
	0, 59, 64, 1, 1, 0, 60, 63, 1, 1
};

/* town_block_3: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5881
   CPC asset id: town_block_3
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_3_WIDTH 5
static const UBYTE harCpcTownBlock3Tiles[25] = {
	0, 0, 42, 1, 1, 0, 42, 65, 1, 1, 59, 64, 64, 1, 1, 61,
	64, 63, 1, 1, 60, 64, 64, 1, 1
};

/* town_block_4: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5882
   CPC asset id: town_block_4
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_4_WIDTH 5
static const UBYTE harCpcTownBlock4Tiles[25] = {
	0, 62, 64, 1, 1, 59, 64, 63, 1, 1, 61, 64, 64, 1, 1, 60,
	64, 64, 1, 1, 0, 62, 63, 1, 1
};

/* town_block_5: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5883
   CPC asset id: town_block_5
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_5_WIDTH 2
static const UBYTE harCpcTownBlock5Tiles[10] = {
	0, 0, 45, 1, 1, 0, 0, 46, 1, 1
};

/* town_block_6: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5884
   CPC asset id: town_block_6
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_6_WIDTH 2
static const UBYTE harCpcTownBlock6Tiles[10] = {
	64, 64, 64, 1, 1, 64, 64, 63, 1, 1
};

/* town_block_7: CPC town/building block
   CPC source: HarrierAttackSourceNew2_alt_CRTC_CART16.asm:5885
   CPC asset id: town_block_7
   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */
#define HAR_CPC_TOWN_BLOCK_7_WIDTH 4
static const UBYTE harCpcTownBlock7Tiles[20] = {
	0, 43, 64, 1, 1, 0, 59, 63, 1, 1, 0, 60, 64, 1, 1, 0,
	44, 64, 1, 1
};

static const UBYTE* const harCpcTownBlockTiles[HAR_CPC_TOWN_BLOCK_COUNT] = {
	harCpcTownBlock0Tiles,
	harCpcTownBlock1Tiles,
	harCpcTownBlock2Tiles,
	harCpcTownBlock3Tiles,
	harCpcTownBlock4Tiles,
	harCpcTownBlock5Tiles,
	harCpcTownBlock6Tiles,
	harCpcTownBlock7Tiles,
};

static const UBYTE harCpcTownBlockWidths[HAR_CPC_TOWN_BLOCK_COUNT] = {
	1, 2, 2, 5, 5, 2, 2, 4
};

#endif
