"""Rebuild the tiny Paula bomber loop and optional listening previews."""
from pathlib import Path
import wave

ROOT = Path(__file__).resolve().parents[1]

def generate():
    samples = [32*((i*4 % 256)/128-1)+32*((i*5 % 256)/128-1) for i in range(256)]
    for _ in range(4):
        samples = [(samples[(i-1)%256]+2*samples[i]+samples[(i+1)%256])/4 for i in range(256)]
    return bytes(round(v)&255 for v in samples)

if __name__ == "__main__":
    samples=generate()
    header="/* Generated by tools/generate-bomber-drone.py; one 256-byte Paula loop. */\n"
    header+="EMBED_CHIP sfxBomberDrone[] = {"+",".join(map(str,samples))+"};\n"
    (ROOT/"amiga/assets/enhanced/bomber_drone.h").write_text(header,encoding="ascii")
    preview=ROOT/".tmp"; preview.mkdir(exist_ok=True)
    with wave.open(str(preview/"bomber-drone-preview.wav"),"wb") as out:
        out.setparams((1,1,round(3546895/700),0,"NONE","not compressed"))
        out.writeframes(bytes(128+round((v if v<128 else v-256)*10/64) for v in samples)*40)
    raw=(ROOT/"amiga/assets/sfx/ground_miss_1.raw").read_bytes()
    burst=raw[:len(raw)//6*2]+raw
    with wave.open(str(preview/"depot-bo-boom-preview.wav"),"wb") as out:
        out.setparams((1,1,11025,0,"NONE","not compressed"))
        out.writeframes(bytes(v^128 for v in burst))
