#!/usr/bin/env python3
"""Promote selected audited CPC assets into Amiga runtime C data."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


PROMOTED_PLUS_SPRITES: list[tuple[str, str]] = [
    ("harrier_flying_left", "sprite_pixel_data1"),
    ("harrier_flying_right", "sprite_pixel_data2"),
    ("harrier_landing_left", "sprite_pixel_data4"),
    ("harrier_landing_right", "sprite_pixel_data3"),
    ("enemy_plane_flying_left", "sprite_pixel_data5"),
    ("enemy_plane_flying_right", "sprite_pixel_data6"),
    ("enemy_plane_broken_left", "sprite_pixel_data7"),
    ("enemy_plane_broken_right", "sprite_pixel_data8"),
    ("carrier_body", "sprite_pixel_data10"),
    ("carrier_back", "sprite_pixel_data11"),
    ("carrier_front", "sprite_pixel_data12"),
    ("carrier_top", "sprite_pixel_data13"),
    ("carrier_top_2", "sprite_pixel_data14"),
    ("gunship_left", "sprite_pixel_data15"),
    ("gunship_right", "sprite_pixel_data16"),
    ("wingman_flying_left", "sprite_pixel_data_wingmanflying1"),
    ("wingman_flying_right", "sprite_pixel_data_wingmanflying2"),
    ("wingman_landed_left", "sprite_pixel_data_wingmanlanded1"),
    ("wingman_landed_right", "sprite_pixel_data_wingmanlanded2"),
    ("parachute", "sprite_pixel_data_parachute"),
]

PROMOTED_TOWN_BLOCKS: list[tuple[str, str]] = [
    (f"town_block_{index}", f"town_block_{index}") for index in range(8)
]

TOWN_BLOCK_HEIGHT = 5


def c_ident(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name).upper()


def format_array(values: list[int], indent: str = "\t") -> str:
    lines: list[str] = []
    for index in range(0, len(values), 16):
        chunk = values[index : index + 16]
        lines.append(indent + ", ".join(str(value) for value in chunk))
    return ",\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Promote selected CPC asset-audit sprites into a C header.")
    parser.add_argument("--input", type=Path, default=Path("amiga/assets/generated/cpc/cpc_plus_sprites.json"))
    parser.add_argument("--objects-input", type=Path, default=Path("amiga/assets/generated/cpc/cpc_object_blocks.json"))
    parser.add_argument("--output", type=Path, default=Path("amiga/assets/cpc_promoted_assets.h"))
    args = parser.parse_args()

    sprites = json.loads(args.input.read_text(encoding="utf-8"))
    by_id = {sprite["asset_id"].lower(): sprite for sprite in sprites}
    objects = json.loads(args.objects_input.read_text(encoding="utf-8"))
    objects_by_id = {obj["asset_id"].lower(): obj for obj in objects}

    missing = [source_id for _friendly, source_id in PROMOTED_PLUS_SPRITES if source_id.lower() not in by_id]
    if missing:
        raise SystemExit(f"Missing audited CPC Plus sprites: {', '.join(missing)}")
    wrongly_encoded = [
        source_id
        for _friendly, source_id in PROMOTED_PLUS_SPRITES
        if by_id[source_id.lower()].get("kind") != "cpc_plus_sprite_pixels"
        or by_id[source_id.lower()].get("graphics_mode") != "cpc_plus_direct_pen_indices"
    ]
    if wrongly_encoded:
        raise SystemExit(
            "Refusing to promote CPC Plus sprites without direct-pen metadata: "
            + ", ".join(wrongly_encoded)
        )
    missing_objects = [source_id for _friendly, source_id in PROMOTED_TOWN_BLOCKS if source_id.lower() not in objects_by_id]
    if missing_objects:
        raise SystemExit(f"Missing audited CPC object blocks: {', '.join(missing_objects)}")

    lines: list[str] = [
        "/* Generated by tools/promote_cpc_assets.py. Do not hand-edit raw arrays.",
        "   Source of truth: amiga/assets/generated/cpc/cpc_plus_sprites.json",
        "                    amiga/assets/generated/cpc/cpc_object_blocks.json",
        "   Polished/native derivatives should be separate assets that cite these source ids. */",
        "#ifndef HAR_CPC_PROMOTED_ASSETS_H",
        "#define HAR_CPC_PROMOTED_ASSETS_H",
        "",
        "#define HAR_CPC_PROMOTED_ASSET_COUNT %d" % len(PROMOTED_PLUS_SPRITES),
        "#define HAR_CPC_TOWN_BLOCK_COUNT %d" % len(PROMOTED_TOWN_BLOCKS),
        "#define HAR_CPC_TOWN_BLOCK_HEIGHT %d" % TOWN_BLOCK_HEIGHT,
        "",
    ]

    for friendly_name, source_id in PROMOTED_PLUS_SPRITES:
        sprite = by_id[source_id.lower()]
        symbol = c_ident(friendly_name)
        pixels = [value for row in sprite["pixels"] for value in row]
        lines.extend(
            [
                f"/* {friendly_name}: {sprite.get('name', source_id)}",
                f"   CPC source: {sprite.get('source', '?')}",
                f"   CPC asset id: {sprite.get('asset_id', source_id)} */",
                f"#define HAR_CPC_{symbol}_WIDTH {sprite['width']}",
                f"#define HAR_CPC_{symbol}_HEIGHT {sprite['height']}",
                f"static const UBYTE harCpc{''.join(part.capitalize() for part in friendly_name.split('_'))}Pixels[{len(pixels)}] = {{",
                format_array(pixels),
                "};",
                "",
            ]
        )

    town_symbols: list[str] = []
    town_widths: list[int] = []
    for friendly_name, source_id in PROMOTED_TOWN_BLOCKS:
        obj = objects_by_id[source_id.lower()]
        symbol_suffix = "".join(part.capitalize() for part in friendly_name.split("_"))
        symbol = f"harCpc{symbol_suffix}Tiles"
        raw_values = list(obj.get("raw_values", []))
        if raw_values and raw_values[-1] == 255:
            raw_values = raw_values[:-1]
        width = (len(raw_values) + TOWN_BLOCK_HEIGHT - 1) // TOWN_BLOCK_HEIGHT
        padded_count = width * TOWN_BLOCK_HEIGHT
        if len(raw_values) < padded_count:
            raw_values.extend([0] * (padded_count - len(raw_values)))
        town_symbols.append(symbol)
        town_widths.append(width)
        lines.extend(
            [
                f"/* {friendly_name}: CPC town/building block",
                f"   CPC source: {obj.get('source', '?')}",
                f"   CPC asset id: {obj.get('asset_id', source_id)}",
                "   Layout: column-major, HAR_CPC_TOWN_BLOCK_HEIGHT rows per column. */",
                f"#define HAR_CPC_{c_ident(friendly_name)}_WIDTH {width}",
                f"static const UBYTE {symbol}[{len(raw_values)}] = {{",
                format_array(raw_values),
                "};",
                "",
            ]
        )

    lines.append("static const UBYTE* const harCpcTownBlockTiles[HAR_CPC_TOWN_BLOCK_COUNT] = {")
    for symbol in town_symbols:
        lines.append(f"\t{symbol},")
    lines.append("};")
    lines.append("")
    lines.append("static const UBYTE harCpcTownBlockWidths[HAR_CPC_TOWN_BLOCK_COUNT] = {")
    lines.append(format_array(town_widths))
    lines.append("};")
    lines.append("")

    lines.append("#endif")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote promoted CPC runtime header: {args.output}")
    print(f"Promoted {len(PROMOTED_PLUS_SPRITES)} Plus sprite assets and {len(PROMOTED_TOWN_BLOCKS)} town blocks")


if __name__ == "__main__":
    main()
